version: '3'
services:
  cloud-config:
    image: registry.heroku.com/geek-spring-cloud-config/web:latest
    ports:
      - 8888

  shop-frontend-app:
    image: shop-frontend-app:latest
    ports:
      - 8080:80
    depends_on:
      - shop-admin-app
      - shop-backend-api-app
      - picture-service-app

  shop-admin-app:
    image: registry.heroku.com/geek-shop-admin-app/web:latest
    ports:
      - 8080
    volumes:
      - ./storage:/var/storage
    environment:
      - PROFILE=dock
      - CONFIG_SERVER_URL=http://cloud-config:8888
    command: bash -c "/apps/wait-for-service.sh db 3306 && /apps/wait-for-service.sh cloud-config 8888 && /apps/entrypoint.sh"
    depends_on:
      - db
      - redis
      - cloud-config

  shop-backend-api-app:
    image: registry.heroku.com/geek-shop-backend-api-app/web:latest
    ports:
      - 8085:8080
    environment:
      - PROFILE=dock
      - CONFIG_SERVER_URL=http://cloud-config:8888
    command: bash -c "/apps/wait-for-service.sh db 3306 && /apps/wait-for-service.sh cloud-config 8888 && /apps/entrypoint.sh"
    depends_on:
      - db
      - redis
      - cloud-config

  picture-service-app:
    image: registry.heroku.com/geek-shop-picture-service-api/web:latest
    ports:
      - 8080
    volumes:
      - ./storage:/var/storage
    environment:
      - PROFILE=dock
      - CONFIG_SERVER_URL=http://cloud-config:8888
    command: bash -c "/apps/wait-for-service.sh db 3306 && /apps/wait-for-service.sh cloud-config 8888 && /apps/entrypoint.sh"
    depends_on:
      - db
      - cloud-config

  db:
    #    image: postgres
    #    restart: always
    #    environment:
    #      POSTGRES_PASSWORD: password
    #    ports:
    #    - 5432:5432

    image: mysql:8.0.28
    environment:
      MYSQL_USER_PASSWORD: "mikhail1988"
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

volumes:
  mysql-data:
